[package]
name = "ridesharing-chengdu-rust-main"
version = "0.1.0"
edition = "2024"

[lib]
name = "_rust_core"
crate-type = ["cdylib", "rlib"]

[features]
default = ["embedding"]
embedding = ["pyo3/auto-initialize"]
python-extension = ["pyo3/extension-module"]

[dependencies]
anyhow = "1"
axum = "0.8"
csv = "1"
futures = "0.3"
h3o = { version = "0.11.0", default-features = false }
pyo3 = { version = "0.23" }
rand = "0.9"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.8"
tower-http = { version = "0.6", features = ["cors"] }
